### ISSUE TITLE
Add "Recently added packages" to the home page

### ISSUE THREAD

**Issue by ravage84** [cakephp/plugins.cakephp.org#78] opened 2013-07-02 11:23 UTC
Add "Recently added packages" to the home page.

There you can find the last added 5-10 packages.

**Comment by josegonzalez** [comment] 2018-01-18 08:08
Duplicate of #78.

**Closed by josegonzalez** 2018-01-18 08:08 UTC

**Comment by ravage84** [comment] 2018-01-22 15:42
@josegonzalez this is a duplicate of itself? 😕

**Comment by josegonzalez** [comment] 2018-01-22 15:49
I meant #77.
